### ISSUE TITLE
Make sure sync doesn't import measurements created less than 15 minutes ago

### ISSUE THREAD

**Issue by mikepsinn** [QuantiModo/QuantiModo-SDK-Android#9]
We can use a request like this to get measurements updated since the last syncTime but were created more than 15 minutes ago to ensure that we don't overwrite any changes made to new measurements after the sync process began.

**Comment by mikepsinn** [comment]
https://app.quantimo.do:443/api/v1/measurements?variableName=Overall%20Mood&createdAt=(lt)2015-11-12T00%3A00%3A00&updatedAt=(gt)2015-10-10T00%3A00%3A00

**Comment by buster92** [comment]
We will paused this until v2 API is done. The branch to implement this, is: https://github.com/QuantiModo/QuantiModo-SDK-Android/tree/feature/update_get_measurements
